terms_by_type = {
   'Corporation': ['company', 'incorporated', 'corporation', 'corp.', 'corp', 'inc',
      '& co.', '& co', 'inc.', 's.p.a.', 'n.v.', 'a.g.', 'ag', 'nuf', 's.a.', 's.f.',
      'oao', 'co.', 'co'
   ],
   'General Partnership': ['soc.col.', 'stg', 'd.n.o.', 'ltda.', 'v.o.s.', 'a spol.',
      u've\xc5\x99. obch. spol.', 'kgaa', 'o.e.', 's.f.', 's.n.c.', 's.a.p.a.', 'j.t.d.',
      'v.o.f.', 'sp.j.', 'og', 'sd', ' i/s', 'ay', 'snc', 'oe', 'bt.', 's.s.', 'mb',
      'ans', 'da', 'o.d.', 'hb', 'pt'
   ],
   'Joint Stock / Unlimited': ['unltd', 'ultd', 'sal', 'unlimited', 'saog', 'saoc', 'aj',
      'yoaj', 'oaj', 'akc. spol.', 'a.s.'
   ],
   'Joint Venture': ['esv', 'gie', 'kv.', 'qk'],
   'Limited': ['pty. ltd.', 'ltd', 'pty ltd', 'ltd', 'l.t.d.', 'bvba', 'd.o.o.', 'ltda', 'gmbh',
      'g.m.b.h', 'kft.', 'kht.', 'zrt.', 'ehf.', 's.a.r.l.', 'd.o.o.e.l.', 's. de r.l.',
      'b.v.', 'tapui',
      'sp. z.o.o.', 'sp. z o.o.', 'spółka z o.o.',
      's.r.l.', 's.l.', 's.l.n.e.', 'ood', 'oy', 'rt.',
      'teo', 'uab', 'scs', 'sprl', 'limited', 'bhd.', 'sdn. bhd.', 'sdn bhd', 'as',
      'lda.', 'tov', 'pp'
   ],
   'Limited Liability Company': ['pllc', 'llc', 'l.l.c.', 'plc.', 'plc', 'hf.', 'oyj',
      'a.e.', 'nyrt.', 'p.l.c.', 'sh.a.', 's.a.', 's.r.l.', 'srl.', 'srl', 'aat', '3at', 'd.d.',
      's.r.o.', 'spol. s r.o.', 's.m.b.a.', 'smba', 'sarl', 'nv', 'sa', 'aps',
      'a/s', 'p/s', 'sae', 'sasu', 'eurl', 'ae', 'cpt', 'as', 'ab', 'asa', 'ooo', 'dat',
      'vat', 'zat', 'mchj', 'a.d.'
   ],
   'Limited Liability Limited Partnership': ['lllp', 'l.l.l.p.'],
   'Limited Liability Partnership': ['llp', 'l.l.p.', 'sp.p.', 's.c.a.', 's.c.s.'],
   'Limited Partnership': ['gmbh & co. kg', 'gmbh & co. kg', 'lp', 'l.p.', 's.c.s.',
      's.c.p.a', 'comm.v', 'k.d.', 'k.d.a.', 's. en c.', 'e.e.', 's.a.s.', 's. en c.',
      'c.v.', 's.k.a.', 'sp.k.', 's.cra.', 'ky', 'scs', 'kg', 'kd', 'k/s', 'ee', 'secs',
      'kda', 'ks', 'kb','kt'
   ],
   'Mutual Fund': ['sicav'],
   'No Liability': ['nl'],
   'Non-Profit': ['vzw', 'ses.', 'gte.'],
   'Private Company': ['private', 'pte', 'xk'],
   'Professional Corporation': ['p.c.', 'vof', 'snc'],
   'Professional Limited Liability Company': ['pllc', 'p.l.l.c.'],
   'Sole Proprietorship': ['e.u.', 's.p.', 't:mi', 'tmi', 'e.v.', 'e.c.', 'et', 'obrt',
      'fie', 'ij', 'fop', 'xt'
   ],
   'Asociación en Participación': ['a.p.', 'a. en p.'],
   'Asociación Civil': ['ac', 'a.c.'],
   'Aktieselskap': ['a/s'],
   'Aktiebolag': ['a.b.', 'ab'],
   'Agrupamento Complementar de Empresas': ['ace', 'a.c.e.'],
   'Aktzionerno Druzhestvo': ['ad', 'a.d.'],
   'Anonymos Etairia': ['ae', 'a.e.'],
   'Aktiengesellschaft': ['ag', 'a.g.'],
   'Andelslag': ['al', 'a.l.'],
   'Andelsselskab': ['amba', 'a.m.b.a.'],
   'Ansvarlig selskap': ['ans', 'a.n.s.'],
   'Publikt Aktiebolag': ['apb', 'a.p.b.'],
   'Anpartsselskab': ['aps', 'a.p.s.'],
   'Aksjeselskap': ['as'],
   'Allmennaksjeselskap': ['asa', 'a.s.a.'],
   'Aruba Vrijgestelde Vennootschap': ['avv', 'a.v.v.'],
   'Besloten Vennootschap': ['b.v.' 'bv'],
   'Beperk': ['bpk', 'b.p.k.'],
   'Beteti társaság': ['bt', 'b.t.'],
   'Besloten Vennootschap met Beper…': ['b.v.b.a' 'bvba.'],
   'Commanditaire Vennootschap': ['c.v.', 'cv'],
   'Compania Anonima': ['ca', 'c.a.'],
   'Commanditaire Vennootschap op Aa…': ['cva', 'c.v.a.'],
   'Commanditaire Vennootschap op A…': ['cvoa', 'C.c.v.o.a.'],
   'Delniska druzba': ['dd', 'd.d.'],
   'Družba z neomejeno odgovornostjo': ['d.n.o.', 'dno'],
   'Druzba z omejeno odgovornostjo': ['d.o.o.' 'doo'],
   'Doing Business As': ['d/b/a', 'dba'],
   'Selskap med delt ansar': ['da', 'd.a.'],
   'Eingetragener Verein': ['e.v.' 'ev'],
   'Eterrorrythmos': ['ee', 'e.e.'],
   'Eingetragene Erwerbsgesellschaft': ['eeg', 'e.e.g.'],
   'Empresa Individual de Responsabilidad Limitada': ['eirl' 'e.i.r.l.'],
   'Exempted Limited Partnership': ['elp', 'e.l.p.'],
   'Ednolichno Druzhestvo s Ogranic…': ['eood', 'e.o.o.d.'],
   'Etairia periorismenis evthinis': ['epe', 'e.p.e.'],
   'Enterprise Unipersonnelle à Res…': ['eurl', 'e.u.r.l.'],
   'Gesellschaft burgerlichen Rechts': ['gbr', 'g.b.r.'],
   'Gewone Commanditaire Vennootscha…': ['gcv' 'g.c.v.'],
   'Gesellschaft mit beschränkter…': ['gesmbh', 'g.e.s.m.b.h.'],
   "Groupement d'intéret économique": ['gie', 'g.i.e.'],
   'Gesellschaft mit beschränkter H…': ['gmbh', 'g.m.b.h.'],
   'Handelsbolag': ['hb', 'h.b.'],
   'Hlutafelag': ['hf', 'h.f.'],
   'Interessentskab': ['i/s', 'is'],
   'International Business Company': ['ibc', 'i.b.c.'],
   'Javno trgovacko drustvo': ['j.t.d.', 'jtd'],
   'Komanditna druzba': ['k.d.', 'kd'],
   'Komanditna delniska druzba': ['k.d.d.', 'kdd'],
   'komanditni spolecnost': ['k.s.', 'ks'],
   'Kommanditselskab': ['k/s'],
   'Kommanditaktieselskab': ['ka/s', 'k.a.s.'],
   'Kommanditbolag': ['kb', 'k.b.'],
   'Komanditno drushestwo': ['kd', 'k.d.'],
   'Komanditno drushestwo s akzii': ['kda', 'k.d.a.'],
   'korlátolt felelösségû társaság': ['kft', 'k.f.t.'],
   'Kommanditgesellschaft': ['kg', 'k.g.'],
   'Kommanditgesellschaft auf Aktie…': ['kgaa', 'k.g.a.a.'],
   'Kabushiki Kaishi': ['kk', 'k.k.'],
   'közkereseti társaság': ['kkt', 'k.k.t.'],
   'Kollektiv Sirket': ['kol. srk'],
   'Komandit Sirket': ['kom. srk'],
   'Kommandittselskap': ['ks'],
   'Közös vállalat': ['kv'],
   'Kommandiittiyhtiö': ['ky', 'k.y.'],
   'Sociedade por Quotas Limitada': ['lda', 'l.d.a.'],
   'Limited Duration Company': ['ldc', 'l.d.c.'],
   'Sociedade por Quotas de Respons…': ['ltda' 'ltda.'],
   'Limitée': ['Ltée.', 'Ltée'],
   'National Association': ['n.a.', 'na'],
   'iNTermediary': ['nt', 'n.t.'],
   'Naamloze Vennootschap': ['nv', 'n.v.'],
   'Omorrythmos': ['oe', 'o.e.'],
   'Offene Handelsgesellschaft': ['ohg', 'o.h.g.'],
   'Druzhestvo s Ogranichena Otgovor…': ['ood', 'o.o.d.'],
   'Osaühing': ['oü', 'o.ü.'],
   'Osakeyhtiö': ['oy', 'oy.'],
   'Julkinen osakeyhtiö': ['oyj', 'oyj.'],
   'Proprietary Limited': ['p/l', 'p.l.'],
   'Public Company Limited by Sha…': ['pc ltd', 'pc ltd.'],
   'Public Limited Company': ['plc', 'plc.'],
   'Penenaman Modal Asing': ['pma', 'p.m.a.'],
   'Penanaman Modal Dalam Negeri': ['pmdn', 'p.m.d.n.'],
   'Private Company limited by share…': ['prc', 'p.r.c.'],
   'Private company limited by… ': ['prp. ltd.', 'prp ltd'],
   'Perseroan Terbuka': ['pt', 'pt.'],
   'Proprietary': ['pty.', 'pty'],
   'Riiklik Aktsiaselts': ['ras',	'r.a.s.'],
   'Részvénytársaság': ['rt', 'r.t.'],
   'Sociedad de Responsabilid…': ['s. de r.l.', 's.r.l.'],
   'Sociedad en Comandita': ['s. en c.', 's.c.'],
   'Sociedad en Nombre Colect…': ['s. en n.c.', 'snc'],
   'Sociedade por Ações': ['s.a.', 'sa'],
   'Sociedad Anónima Inscrita…': ['s.a.i.c.a.', 'saica'],
   'Sociedad en commandita': ['s.c.', 'sc'],
   'Sociedade em Comandita Simple…': ['scs', 'scs'],
   'Sociedades Anônimas': ['s/a', 's.a.'],
   'Sociedad Anónima de Capital…': ['sa de cv', 's.a. de c.v.'],
   'Sociedad Anonima Financiera de…': ['safi', 's.a.f.i.'],
   'Societa in Accomandita per Azio…' : ['sapa', 's.a.p.a.'],
   'Société à responsabilité limité…'	: ['sarl', 's.a.r.l.'],
   'Societá in Accomandita Semplice' : ['sas', 's.a.s.'],
   'Société civile': ['sc', 's.c.'],
   'Societate in còmandita pe actiun…': ['sca', 's.c.a.'],
   'Sociedade em Conta de Participac…': ['scp', 's.c.p.'],
   'Societate in comandita simpla': ['scs', 's.c.s.'],
   'Sendirian Berhad': ['sdn bhd', 'sdn bhd.'],
   'Société en Nom Collectif': ['senc', 's.e.n.c.'],
   'Sociedade gestora de participaç…': ['sgps', 's.g.p.s.'],
   'Spólka komandytowa': ['sk', 's.k.'],
   'Société de Participation Fin…': ['soparfi'],
   'Societe en participation': ['sp', 's.p.'],
   'Spólka z ograniczona odpo…': ['sp. z.o.o.'],
   'Società per Azioni': ['spa', 's.p.a.'],
   'Spolecnost s rucenim ome…': ['spol s.r.o.', 'spol'],
   'Société Privée à Responsabilité…': ['sprl', 's.p.r.l.'],
   'Societate cu raspondere limitata': ['srl', 's.r.l.'],
   'Tiha druzba': ['td', 't.d.'],
   'Türk Limited Sirket': ['tls', 't.l.s.'],
   'Verejna obchodni spolecnost': ['v.o.s.', 'vos'],
   'Volkseigner Betrieb': ['veb', 'v.e.b.'],
   'Vennootschap onder Firma': ['vof', 'v.o.f.']
}

terms_by_country = {
   'Albania': ['sh.a.', 'sh.p.k.'],
   'Argentina': ['s.a.', 's.r.l.', 's.c.p.a', 'scpa', 's.c.e i.', 's.e.', 's.g.r',
      'soc.col.'
   ],
   'Australia': ['nl', 'pty. ltd.', 'pty ltd'],
   'Austria': ['e.u.', 'stg', 'gesbr', 'a.g.', 'ag', 'og', 'kg'],
   'Belarus': ['aat', '3at'],
   'Belgium': ['esv', 'vzw', 'vof', 'snc', 'comm.v', 'scs', 'bvba', 'sprl', 'cvba',
      'cvoa', 'sca', 'sep', 'gie'
   ],
   'Bosnia / Herzegovina': ['d.d.', 'a.d.', 'd.n.o.', 'd.o.o.', 'k.v.', 's.p.'],
   'Brazil': ['ltda', 's.a.', 'pllc', 'ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
   'Bulgaria': ['ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
   'Cambodia': ['gp', 'sm pte ltd.', 'pte ltd.', 'plc ltd.', 'peec', 'sp'],
   'Canada': ['gp', 'lp', 'sp'],
   'Chile': ['eirl', 's.a.', 'sgr', 's.g.r.', 'ltda', 's.p.a.', 'sa', 's. en c.',
      'ltda.'
   ],
   'Columbia': ['s.a.', 'e.u.', 's.a.s.', 'suc. de descendants', 'sca'],
   'Croatia': ['d.d.', 'd.o.o.', 'obrt'],
   'Czech Republic': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'v.o.s.', u've\xc5\x99. obch. spol.', 'a spol.', 'k.s.', 'kom. spol.', 'kom. spol.'],
   'Denmark': ['i/s', 'a/s', 'k/s', 'p/s', 'amba', 'a.m.b.a.', 'fmba', 'f.m.b.a.', 'smba',
      's.m.b.a.', 'g/s'
   ],
   'Dominican Republic': ['c. por a.', 'cxa', 's.a.', 's.a.s.', 'srl.', 'srl', 'eirl.', 'sa',
      'sas'
   ],
   'Ecuador': ['s.a.', 'c.a.', 'sa', 'ep'],
   'Egypt': ['sae'],
   'Estonia': ['fie'],
   'Finland': ['t:mi', 'tmi', 'as oy', 'as.oy', 'ay', 'ky', 'oy', 'oyj', 'ok'],
   'France': ['sicav', 'sarl', 'sogepa', 'ei', 'eurl', 'sasu', 'fcp', 'gie', 'sep', 'snc',
      'scs', 'sca', 'scop', 'sem', 'sas'
   ],
   'Germany': ['gmbh & co. kg', 'gmbh & co. kg', 'e.g.', 'e.v.', 'gbr', 'ohg', 'partg',
      'kgaa', 'gmbh', 'g.m.b.h.', 'ag'
   ],
   'Greece': ['a.e.', 'ae', 'e.e.', 'ee', 'epe', 'e.p.e.', 'mepe', 'm.e.p.e.', 'o.e.',
      'oe', 'ovee', 'o.v.e.e.'
   ],
   'Guatemala': ['s.a.', 'sa'],
   'Haiti': ['sa'],
   'Hong Kong': ['ltd', 'unltd', 'ultd', 'limited'],
   'Hungary': ['e.v.', 'e.c.', 'bt.', 'kft.', 'kht.', 'kkt.', 'k.v.', 'zrt.', 'nyrt',
      'ev', 'ec', 'rt.'
   ],
   'Iceland': ['ehf.', 'hf.', 'ohf.', 's.f.', 'ses.'],
   'India': ['pvt. ltd.', 'ltd.', 'psu', 'pse'],
   'Indonesia': ['ud', 'fa', 'pt'],
   'Ireland': ['cpt', 'teo'],
   'Israel': ['b.m.', 'bm', 'ltd', 'limited'],
   'Italy': ['s.n.c.', 's.a.s.', 's.p.a.', 's.a.p.a.', 's.r.l.', 's.c.r.l.', 's.s.'],
   'Latvia': ['as', 'sia', 'ik', 'ps', 'ks'],
   'Lebanon': ['sal'],
   'Lithuania': ['uab', 'ab', 'ij', 'mb'],
   'Luxemborg': ['s.a.', 's.a.r.l.', 'secs'],
   'Macedonia': ['d.o.o.', 'd.o.o.e.l', 'k.d.a.', 'j.t.d.', 'a.d.', 'k.d.'],
   'Malaysia': ['bhd.', 'sdn. bhd.'],
   'Mexico': ['s.a.', 's. de. r.l.', 's. en c.', 's.a.b.', 's.a.p.i.'],
   'Mongolia': ['xk', 'xxk'],
   'Netherlands': ['v.o.f.', 'c.v.', 'b.v.', 'n.v.'],
   'New Zealand': ['tapui', 'ltd', 'limited'],
   'Nigeria': ['gte.', 'plc', 'ltd.', 'ultd.'],
   'Norway': ['asa', 'as', 'ans', 'ba', 'bl', 'da', 'etat', 'fkf', 'hf', 'iks', 'kf',
      'ks', 'nuf', 'rhf', 'sf'
   ],
   'Oman': ['saog', 'saoc'],
   'Pakistan': ['ltd.', 'pvt. ltd.', 'ltd', 'limited'],
   'Peru': ['sa', 's.a.', 's.a.a.'],
   'Philippines': ['coop.', 'corp.', 'corp', 'ent.', 'inc.', 'inc', 'llc', 'l.l.c.',
      'ltd.'
   ],
   'Poland': ['p.p.', 's.k.a.', 'sp.j.', 'sp.k.', 'sp.p.', 'sp. z.o.o.', 's.c.', 's.a.'],
   'Portugal': ['lda.', 'crl', 's.a.', 's.f.', 'sgps'],
   'Romania': ['s.c.a.', 's.c.s.', 's.n.c.', 's.r.l.', 'o.n.g.', 's.a.'],
   'Russia': ['ooo', 'oao', 'zao', '3ao', 'пао', 'оао', 'ооо'],
   'Serbia': ['d.o.o.', 'a.d.', 'k.d.', 'o.d.'],
   'Singapore': ['bhd', 'pte ltd', 'sdn bhd', 'llp', 'l.l.p.', 'ltd.', 'pte'],
   'Slovenia': ['d.d.', 'd.o.o.', 'd.n.o.', 'k.d.', 's.p.'],
   'Slovakia': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'k.s.', 'kom. spol.', 'v.o.s.', 'a spol.'],
   'Spain': ['s.a.', 's.a.d.', 's.l.', 's.l.l.', 's.l.n.e.', 's.c.', 's.cra', 's.coop',
      'sal', 'sccl'
   ],
   'Sweden': ['ab', 'hb', 'kb'],
   'Switzerland': ['ab', 'sa', 'gmbh', 'g.m.b.h.', 'sarl', 'sagl'],
   'Turkey': ['koop.'],
   'Ukraine': ['dat', 'fop', 'kt', 'pt', 'tdv', 'tov', 'pp', 'vat', 'zat', 'at'],
   'United Kingdom': ['plc.', 'plc', 'cic', 'cio', 'l.l.p.', 'llp', 'l.p.', 'lp', 'ltd.',
      'ltd', 'limited'
   ],
   'United States of America': ['llc', 'inc.', 'corporation', 'incorporated', 'company',
      'limited', 'corp.', 'inc.', 'inc', 'llp', 'l.l.p.', 'pllc', 'and company',
      '& company', 'inc', 'inc.', 'corp.', 'corp', 'ltd.', 'ltd', '& co.', '& co', 'co.',
      'co', 'lp'
   ],
   'Uzbekistan': ['mchj', 'qmj', 'aj', 'oaj', 'yoaj', 'xk', 'xt', 'ok', 'uk', 'qk']
}
